### ISSUE TITLE
Compilation failed for package 'RAD'

### ISSUE THREAD

**Issue by gyxlucy** [Netflix/Surus#9]
Hi,

I'm trying to install the RAD package, but when I follow the given command I got "compilation failed for package ‘RAD’" error and it wouldn't install.

I'm running R 3.2.2 on Mac.

Any help is appreciated! 

Thanks.

**Comment by mmolaro** [comment]
I assume you only care about installing the R package. 

Do you have RTools installed with a C++ compiler? Is your path set correctly?

**Comment by gyxlucy** [comment]
I don't think I have RTools installed as I only find RTools for Windows only.
Is there an RTools for Mac?

**Comment by gyxlucy** [comment]
I'm also trying to install on a Windows machine, and a different error appears "dependecy 'RcppEigen' is not available for package 'RAD'".
Is it about missing a C++ compiler? What would you recommend to install? Sorry I'm not a Windows person.

Thanks for your patience!

**Comment by mmolaro** [comment]
Ah yes of course. Didn't pay attention to the Mac part. On Mac OS X you need the "XCode Command Line Tools" so that R can call the C++ compiler.  Try running "gcc" in terminal on your Mac. 

On Windows the dependency RcppEigen is referring the the Eigen library for numerical linear algebra https://cran.r-project.org/web/packages/RcppEigen/index.html .

On windows RTools will install gcc the GNU compiler collection.

**Comment by gyxlucy** [comment]
Ah thanks so much! I got it installed.

**Comment by gyxlucy** [comment]
Hi, I'm wondering where I can see some instructions or examples of how to
run your RPCA tool? Do you have some sample dataset that I can try to play
with?
